"""Add price_alerts table

Revision ID: 81dbbed78fa6
Revises: acb83c6f93fa
Create Date: 2026-09-30 06:04:28.746813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81dbbed78fa6'
down_revision: Union[str, Sequence[str], None] = 'acb83c6f93fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threshold_direction', sa.String(length=5), nullable=False),
    sa.Column('threshold_price_copper', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("threshold_direction IN ('above', 'below')", name=op.f('ck_price_alerts_valid_direction')),
    sa.CheckConstraint('threshold_price_copper > 0', name=op.f('ck_price_alerts_positive_threshold')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['price_snapshots.id'], name=op.f('fk_price_alerts_snapshot_id_price_snapshots'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_price_alerts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_alerts'))
    )
    op.create_index(op.f('ix_price_alerts_user_id'), 'price_alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_alerts_user_id'), table_name='price_alerts')
    op.drop_table('price_alerts')
    # ### end Alembic commands ###
