"""Add price_thresholds table

Revision ID: acb83c6f93fa
Revises: 94506fd908a5
Create Date: 2026-09-29 05:24:45.729586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb83c6f93fa'
down_revision: Union[str, Sequence[str], None] = '94506fd908a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('price_copper', sa.BigInteger(), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('above', 'below')", name=op.f('ck_price_thresholds_valid_direction')),
    sa.CheckConstraint('price_copper > 0', name=op.f('ck_price_thresholds_positive_threshold')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_price_thresholds_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_thresholds')),
    sa.UniqueConstraint('user_id', 'direction', name=op.f('uq_price_thresholds_user_id_direction'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_thresholds')
    # ### end Alembic commands ###
