"""add unique constraint on region and published_at

Revision ID: afac74876ed5
Revises: c016f8c0f9ee
Create Date: 2026-09-03 11:14:17.243227

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afac74876ed5"
down_revision: str | Sequence[str] | None = "c016f8c0f9ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_price_snapshots_region_published_at",
        "price_snapshots",
        ["region", "published_at"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_price_snapshots_region_published_at", "price_snapshots", type_="unique"
    )
    # ### end Alembic commands ###
