"""create price_snapshots

Revision ID: c016f8c0f9ee
Revises:
Create Date: 2026-09-03 06:16:12.143996

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c016f8c0f9ee"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("region", sa.String(length=8), nullable=False),
        sa.Column("price_copper", sa.BigInteger(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_snapshots_published_at"),
        "price_snapshots",
        ["published_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_snapshots_region"), "price_snapshots", ["region"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_price_snapshots_region"), table_name="price_snapshots")
    op.drop_index(op.f("ix_price_snapshots_published_at"), table_name="price_snapshots")
    op.drop_table("price_snapshots")
    # ### end Alembic commands ###
